version: "3.9"  # optional since v1.27.0
services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root 
      - POSTGRES_DB=ny_taxi 
    volumes:
      - "./data:/var/lib/postgres/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admit@admit.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
